language: node_js
node_js:
  - "8"

install:
  - npm install typescript -g
  - npm install @types/node

script:
  - tsc
  - ls
before_deploy:
  - ls
deploy:
  provider: npm
  skip_cleanup: true
  email: 'dev@gleb.pw'
  api_key: $NPM_TOKEN
