language: node_js
node_js:
  - "8"

install:
  - npm install

script:
  - sh build.sh
  - ls
before_deploy:
  - ls
deploy:
  provider: npm
  skip_cleanup: true
  email: '+@gleb.pw'
  api_key: $NPM_TOKEN
